repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        exclude: >
          (?x)^(
            tests/
          )
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        exclude: >
          (?x)^(
            tests/
          )
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        exclude: >
          (?x)^(
            tests/
          )
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: flake8
        exclude: >
          (?x)^(
            tests/
          )
